### ISSUE TITLE
Missing dependency for selinux::boolean 

### ISSUE THREAD

**Issue by jcbollinger** [voxpupuli/puppet-selinux#387] opened 2024-03-18 16:36 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

The issue was observed with

- Puppet: 7.28
- Ruby:  bundled with PDK 3.0.1
- Distribution: RHEL 7.9
- Module version: 3.4.1, 4.1.0

## How to reproduce (e.g Puppet code you use)

```puppet
class mymodule::myclass {
  selinux::boolean { 'use_nfs_home_dirs': ensure => 'on' }
}
```

## What are you seeing

Spec tests of one of my modules fails with

>  error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'selboolean' (file: /home/me/puppet/environments/production/modules/mymodule/spec/fixtures/modules/selinux/manifests/boolean.pp, line: 40, column: 5) (file: /home/me/puppet/environments/production/modules/mymodule/spec/fixtures/modules/mymodule/manifests/myclass.pp, line: 34) on node mybox.my.org

## What behaviour did you expect instead

Catalog compilation should succeed.

## Output log

See above.

## Any additional information you'd like to impart

I presume that the wanted `selboolean` is the one from puppetlabs-selinux_core, but puppet-selinux's metadata does not express a dependency on that module.  At minimum, adding puppetlabs-selinux_core to my test fixture resolved my test failures.

**Comment by kenyon** [comment] 2024-03-18 21:29
See #355.

**Comment by kenyon** [comment] 2024-03-18 21:30
Closing as a duplicate of #355.

**Closed by kenyon** 2024-03-18 21:30 UTC
Labels: duplicate
