### ISSUE TITLE
Expected parameter 'refpolicy_makefile' of 'Class[Selinux]' to have type Stdlib::Absolutepath

### ISSUE THREAD

**Issue by nmaludy** [voxpupuli/puppet-selinux#212] opened 2017-04-10 12:20 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 
```
$ puppet --verison
3.8.6
```

- Ruby:
```
$ ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

- Distribution:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

- Module version:
```
$ cat /etc/puppet/environments/production/modules/selinux/metadata.json | head -n 3
{
  "name": "puppet-selinux",
  "version": "1.0.0",
```

## How to reproduce (e.g Puppet code you use)
Update to puppet-selinux v1.0.0 and run the simple manifest:
```
#
class encore_rp::profile::selinux {
  class { '::selinux':
    mode => 'permissive',
  }
}
```

## What are you seeing
The following error occurs when running `puppet agent -t `:

```
[root@nickpuppet6 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Expected parameter 'refpolicy_makefile' of 'Class[Selinux]' to have type Stdlib::Absolutepath, got String at /etc/puppet/environments/production/modules/encore_rp/manifests/profile/selinux.pp:3 on node xxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## What behaviour did you expect instead
The documented "Basic usage" in the readme to work without error.

**Comment by oranenj** [comment] 2017-04-16 17:44
The selinux module now uses puppet types for validation, which requires Puppet 4.

I will close this issue, as Puppet 3.8.6 is not supported by 1.0.0 anymore. Puppet 3 is EOL, and I recommend you upgrade to Puppet 4 if at all possible. It's much better in addition to being actually supported.

If you can use the future parser, you can make the module 3.8.7 future parser -compatible by replacing all mentions of  `Stdlib::Absolutepath` with `String`. This makes the module a bit more brittle since the parameters won't be validated as paths, but it'll work.

**Closed by oranenj** 2017-04-16 17:44 UTC
Labels: wont-fix

**Comment by oranenj** [comment] 2017-04-16 17:48
Given that some EL7 users might be stuck with puppet 3.8 for various reasons, I might be persuaded to merge a patch to implement future parser -compatibility. Full Puppet 3 compatibility will not happen though, sorry :)

**Comment by laurosn** [comment] 2017-08-07 23:57
I have the same issue with Puppet 4 and Centos 7.
`puppet --version
4.10.5`
My class:
`class camara_profiles::portalphp::selinux {
  class { '::selinux':
    mode => 'disabled',
  }
}`

And when i run the agent:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Expected parameter 'refpolicy_makefile' of 'Class[Selinux]' to have type Stdlib::Absolutepath, got String at /etc/puppetlabs/code/environments/test/modules/camara_profiles/manifests/portalphp/selinux.pp:2 on node vvmctphp01.redecamara.camara.gov.br`

**Comment by vinzent** [comment] 2017-08-08 07:57
@laurosn can't reproduce. 

```
#> BEAKER_set="centos-7-x64" PUPPET_INSTALL_TYPE="agent" be rspec spec/acceptance/class_disabled_spec.rb 
...
centos-7-x64 09:44:40$ yum -y  install puppet-agent
  Loaded plugins: fastestmirror
  Loading mirror speeds from cached hostfile
   * base: pkg.adfinis-sygroup.ch
   * extras: pkg.adfinis-sygroup.ch
   * updates: pkg.adfinis-sygroup.ch
  Resolving Dependencies
  --> Running transaction check
  ---> Package puppet-agent.x86_64 0:1.10.5-1.el7 will be installed
  --> Finished Dependency Resolution
  
  Dependencies Resolved
  
  ================================================================================
   Package            Arch         Version             Repository            Size
  ================================================================================
  Installing:
   puppet-agent       x86_64       1.10.5-1.el7        puppetlabs-pc1        26 M
  
  Transaction Summary

...

selinux class disabled
localhost $ scp /tmp/beaker20170808-9334-19dhzvx centos-7-x64:/tmp/apply_manifest.pp.hrzlkp {:ignore => }
  should run without errors
  Package "selinux-policy-targeted"
    should be installed
  File "/etc/selinux/config"
    content
      should match /^SELINUX=disabled$/
  Command "getenforce"
    stdout
      should match /^Permissive$/
Destroying vagrant boxes
==> centos-7-x64: Forcing shutdown of VM...
==> centos-7-x64: Destroying VM and associated drives...

Finished in 1 minute 5.13 seconds (files took 1 minute 16.17 seconds to load)
4 examples, 0 failures
```

test created in PR: https://github.com/voxpupuli/puppet-selinux/pull/233/files#diff-c0676cae65dbee3d122d29f3330ec81bR6

**Comment by laurosn** [comment] 2017-08-08 12:01
Thanks @vinzent ! I really don't know if it's related with the fact that i have environments with different versions of modules (stdlib, for example). I've already tried to clean cache and restart my puppet server without success. I'll try to run your test.

**Comment by vinzent** [comment] 2017-08-09 07:10
@laurosn I would check your hiera data - I suspect you have set the param there? Please open a new issue if you really have a problem with the param.

**Comment by AnthonyMastrean** [comment] 2018-10-24 22:04
I'm having this same problem on [puppetlabs/centos-7.0-64-puppet](https://app.vagrantup.com/puppetlabs/boxes/centos-7.0-64-puppet).

```
[vagrant@localhost ~]$ puppet --version
4.2.1
```

I installed your module from the forge

```
$ puppet module install puppet-selinux --version 1.6.1
```

And when I evaluate the basic `include` it fails.

```
[vagrant@localhost ~]$ sudo /opt/puppetlabs/bin/puppet apply -e 'include selinux'
Error: Evaluation Error: Error while evaluating a Function Call, Expected parameter 'refpolicy_makefile' of 'Class[Selinux]' to have type Stdlib::Absolutepath, got String  at line 1:1 on node localhost.fios-router.home
```

**Comment by oranenj** [comment] 2018-10-25 07:06
@AnthonyMastrean that version of Puppet is pretty old. Can you try if it happens with a more recent version of 4.x?

**Comment by AnthonyMastrean** [comment] 2018-10-25 13:14
Oh, wow, I hadn't realized these were so out of date (the latest is 2 years
old). Do you know if these Vagrant boxes are "abandoned", then? I'm not
sure how to update the puppet package in one of these, as they don't appear
in "yum list installed". Maybe I'll start with centos/7 and install the
latest puppet.
