### ISSUE TITLE
Puppet Agent 1.5 (Puppet 4.5 Error)

### ISSUE THREAD

**Issue by johnzimm** [voxpupuli/puppet-selinux#97] opened 2016-05-18 19:36 UTC
Just testing an upgrade of the puppet-agent on CentOS 7.

Very basic statement in my profile:

```
class { 'selinux':
  mode => 'permissive',
}
```

Getting the following error message running `puppet agent -t`:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Valid types are targeted, minimum, and mls.  Received:  at /etc/puppetlabs/code/environments/puppet_agent_fixes/modules/selinux/manifests/init.pp:52:3 on node <myhostname.fqdn>
```

Was working fine under puppet 4.4.2 (open source).

**Comment by vinzent** [comment] 2016-12-23 08:44
[init.pp](https://github.com/voxpupuli/puppet-selinux/blob/master/manifests/init.pp) looks up `mode`and ? type` in [params.pp](https://github.com/voxpupuli/puppet-selinux/blob/master/manifests/params.pp). `params.pp` defines the value as `undef`. Thus requering to set a value.

**Comment by vinzent** [comment] 2017-01-06 16:31
@johnzimm still having the problem? can't reproduce with the acceptance test on centos-7.

**Comment by vinzent** [comment] 2017-01-17 07:47
closing this now as acceptance test show no problems and author did not react anymore.

**Closed by vinzent** 2017-01-17 07:47 UTC
